### ISSUE TITLE
Stopped working today, please help with the issue

### ISSUE THREAD

**Issue by VeslavG** [marklagendijk/node-toogoodtogo-watcher#100]
Stopped working today.
Console output below, just changed the user email and user password.
I've tried to clean session data in config file - it did not help.

===
Error during request:
POST https://apptoogoodtogo.com/api/auth/v1/loginByEmail
{
    "device_type": "UNKNOWN",
    "email": "_user_email_",
    "password": "_user_pass_"
}

HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (C:\Users\Slava\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by VeslavG** [comment]
Here is my api part of settings file.
Could it be that we need a new user agent string, since TGTG has updated its app?

{
	"api": {
		"credentials": {
			"email": "user_email",
			"password": "user_pass"
		},
		"session": {},
		"headers": {
			"User-Agent": "TooGoodToGo/**20.6.1 (813)** (iPhone/iPhone 7 (GSM); iOS 13.7; Scale/2.00)"
		},
		"pollingIntervalInMs": 60000,
		"authenticationIntervalInMS": 3600000
	},

**Comment by Slothoncrack** [comment]
Same issue here. Changing v1 to v2 in the Auth-API strings did not help either.

**Comment by RobertPegu** [comment]
Same issue for me, getting 403 Forbidden

**Comment by VeslavG** [comment]
It worked fine today (2021-10-04), last time just about 2 hours ago.

**Comment by RobertPegu** [comment]
Okay, I solved it. I think they dropped support for older apps. I set the user agent to:

`User-Agent": "TooGoodToGo/21.9.0 (813) (iPhone/iPhone 7 (GSM); iOS 15.1; Scale/2.00)`

and now everything looks working fine

**Comment by Slothoncrack** [comment]
Changing the user-agent seems to fix it :)
Use: 
"User-Agent": "TooGoodToGo/21.9.3 (541) (iPhone/iPhone 7 (GSM); iOS 13.6; Scale/2.00)"

It seems to work for me!

**Comment by VeslavG** [comment]
cool, so my assumption about "user agent" is obsolete was correct! indeed it works now.
the default config json requires update with new user agent -  and after that this issue can be closed.
thanks for your help!

**Comment by Kwanaparis** [comment]
HELP! PLEASE!

I am a newer in coding and Linux. I tried to follow the installation process given by the author. But after 
`toogoodtogo-watcher config`
save and exit, and then I tried
`toogoodtogo-watcher watch`,
it reported errors as below. And I found **config.json** set as default again.

ERRORS:
===
Error during request:
POST https://apptoogoodtogo.com/api/auth/v1/loginByEmail
{
"device_type": "UNKNOWN",
"email": "user_email",
"password": "user_pass"
}

HTTPError: Response code 403 (Forbidden)
at Request. (C:\Users\Slava\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\got\dist\source\as-promise\index.js:117:42)
at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by VeslavG** [comment]
https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/100#issuecomment-933730535
change user agent sub-string in config file to below:

"User-Agent": "TooGoodToGo/21.9.3 (541) (iPhone/iPhone 7 (GSM); iOS 13.6; Scale/2.00)"

**Comment by Kwanaparis** [comment]
It still does not work.
Once I tried `toogoodtogo-watcher watch`, it returns errors as mentioned above.
And config.json is set as default. my changes were gone again.
I have tried many times.

**Comment by rayhvh** [comment]
locally it seems to work. on heroku however im getting the same error as mentioned above. using
"User-Agent": "TooGoodToGo/21.9.3 (541) (iPhone/iPhone 7 (GSM); iOS 13.6; Scale/2.00)"

**Comment by MaxWinterstein** [comment]
> Okay, I solved it. I think they dropped support for older app. I set the user agent to:
> 
> `User-Agent": "TooGoodToGo/21.9.0 (813) (iPhone/iPhone 7 (GSM); iOS 15.1; Scale/2.00)`
> 
> and now everything looks working fine

Big thanks from my side, even I came from the python library.

It even seems you can provide anything as long as it differs from the original one.

__broken__:
`"TooGoodToGo/21.9.0 (813) (iPhone/iPhone 7 (GSM); iOS 15.1; Scale/2.00)"`

__working:
```diff
- "TooGoodToGo/21.9.0 (813) (iPhone/iPhone 7 (GSM); iOS 15.1; Scale/2.00)"
+ "TooGoodToGo/21.9.1 (813) (iPhone/iPhone 7 (GSM); iOS 15.1; Scale/2.00)"
```

```diff
- "TooGoodToGo/21.9.0 (813) (iPhone/iPhone 7 (GSM); iOS 15.1; Scale/2.00)"
+ "HP Deskjet 1125"
```

Seems like they start to blocklist user agents? 😲

**Comment by RobertPegu** [comment]
> Seems like they start to blocklist user agents? 😲

I don’t think so. I suppose they are just dropping support for older app versions / iOS releases. But it’s just an opinion

**Comment by MaxWinterstein** [comment]
> > Seems like they start to blocklist user agents? 😲
> 
> I don’t think so. I suppose they are just dropping support for older app versions / iOS releases. But it’s just an opinion

Well, this is just another way of saying the blocklist something. 

Looking at the version history of published iOS releases: https://apps.apple.com/us/app/too-good-to-go/id1060683933

🟢  `21.6.0` is the most recent version that was published and works as user agent.  
🔴  `21.4.0` is the first one that fails, all others older than that (i tested) too.

But, if you play wildly with the user agent you see:
🟢  `TooGoodToGo/99.9.9 (813) (iPhone/iPhone 7 (GSM); iOS 13.7; Scale/2.00)` works fine  
🟢  `TooGoodToGo/10.11.0 (813) (iPhone/iPhone 7 (GSM); iOS 13.7; Scale/2.00)` works fine
🟢  `I should go back to work` works fine

And also you see that:  
🟢  `JohnDoeFooBar/20.6.1 T-1000 Killing Machine` works fine
🔴  `TooGoodTogo/20.6.1 T-1000 Killing Machine` won't work

As a conclusion of this I think they blocklist based on some logic like:
* RegEx out the version string like `r'TooGoodToGo/(.*)\s` and just pass if its not found
* check if > `21.5.0` and bail out if not

**Comment by jfadeuilhe** [comment]
Merci ! 👍🏻

**Comment by jfadeuilhe** [comment]
So it really doesn't work anymore :
   HTTPError: Response code 403 (Forbidden)
Also :
   "device_type": "UNKNOWN",

Can we hope for a corrective version?

**Comment by jfadeuilhe** [comment]
Hello,
I tried again this morning, it still doesn't work.   :(
I updated to version 3.6.6
I have the following message:

----
Error during request:
POST https://apptoogoodtogo.com/api/item/v7/
{
    "favorites_only": true,
    "origin": {
        "latitude": 52.5170365,
        "longitude": 13.3888599
    },
    "radius": 200,
    "user_id": "*******"
}

HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/usr/local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
----

The connection with Telegram is operational , /Stop & /Start displays:
Removed chat Jacques Fadeuilhe (*****)
Added chat Jacques Fadeuilhe (******)

I did a config-reset and re-entered all the parameters, leaving :

"User-Agent": "TooGoodToGo/21.9.0 (813) (iPhone/iPhone 7 (GSM); iOS 15.1; Scale/2.00)"

Can you help me get back on the road?

Merci !
Jacques

**Comment by jfadeuilhe** [comment]
Ok, but I don't think that fixes my problems ...

**Comment by jfadeuilhe** [comment]
Switching to version 3.7.0 this morning: it works!

**Comment by navimondo** [comment]
After trying many combinations/tweaks, my toogoodwatcher service was able
to login on the TGT platform with following code/settings combination:
------------------------------
api.js
    .post("auth/v2/loginByEmail", {
      json: {
        device_type: "ANDROID",
        email: credentials.email,
        password: credentials.password,
      },
    })
"v1/loginByEmail" triggers an error
"v2/loginByEmail" works
If you encounter "HTTPError: Response code 403 (Forbidden)" ensure you are
using the "v2"config.json
 "api": {
"credentials": {
"email": ***@***.***",
"password": "xxxx"
},
"headers": {
"User-Agent": "TooGoodToGo/21.9.0 (813) (iPhone/iPhone 7 (GSM); iOS 15.1;
Scale/2.00)"
  },
------------------------------
--
cpt. Kris De Decker
Business Developer
www.scantainr.com
[image: image.png]
https://www.linkedin.com/in/dedeckerkris/
