### ISSUE TITLE
Can't edit or reset the config file. The same mistake - unexpected string in json...

### ISSUE THREAD

**Issue by VeslavG** [marklagendijk/node-toogoodtogo-watcher#117]
Hello, 

I was making some tweaks to config file, trying to improve something in Telegram integration.

Suddenly, the whole watcher stopped working.
I've tried to reinstall the whole package. Tried to reset the config file, or at least show the path, where config file is stored.
Each time i got below.

Appreciate any ideas on how to fix this and make watcher to work again.
Thanks.

C:\Users\XXX\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\conf\dist\source\index.js:289
            throw error;
            ^

SyntaxError: Unexpected string in JSON at position 805
    at JSON.parse (<anonymous>)
    at Conf._deserialize (C:\Users\XXX\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\conf\dist\source\index.js:67:43)
    at Conf.get store [as store] (C:\Users\XXX\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\conf\dist\source\index.js:277:43)
    at new Conf (C:\Users\XXX\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\conf\dist\source\index.js:130:32)
    at Object.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\lib\config.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

**Comment by VeslavG** [comment]
resolved...
I needed to find the config.json manually. There was a mistake in it (additional comma in telegram settings).
Don't know why config-reset has not reset my config file and continued to re-read it, instead of replacing with empty config template. 
Hopefully this issue will be fixed in future, though it is not that important.
