### ISSUE TITLE
The end is (or might be) near

### ISSUE THREAD

**Issue by marklagendijk** [marklagendijk/node-toogoodtogo-watcher#118]
It is quite likely that the end is near for this application.
The reason is that TooGoodToGo seems to have started protecting their APIs against any automated use.
This is probably caused by malicious automated use of their API. There have been people who offered payed services for 'snatching' TGTG deals.

I have always made it a point to use the public TooGoodToGo API in a respectful and fair manner:
1. There is a minimal polling interval of 15 seconds.
2. The application does not support automatic buying. This would be easy enough to implement, but I consider this a unfair advantage.
3. The application has never employed any 'sneaky tactics' to avoid detection, or by pass any anti-bot mechanisms.
4. I always made it clear that if the company TooGoodToGo doesn't like the way we are using it, they only need to say so, and I would disable this project.

I will continue to follow this approach. This means that if TooGoodToGo will start blocking the application, I will not accept any PRs to attempt to bypass such protection. 

I will accept PRs that:
* Adjust the API code to deal with changes in the API, including things such as headers and request parameters, new authentication mechanisms etc.

I will reject PRs that:
* Try to bypass any bot protection mechanisms, such as CAPTHA's
* Employ 'sneaky tactics' such as timing / location / etc. randomization

I would like to ask everyone to respect this, and not submit any such PR here.

**Comment by jfadeuilhe** [comment]
Okay, I totally agree.

I had thought that the paid offer was in partnership with tgtd and therefore at the origin of the blockages, but if this is not the case it is normal that tgtg seeks to protect itself from these robots.

The automatic purchase would indeed be too much.

Hope it will continue to work!

Thank you

**Comment by Frankdoc** [comment]
Is this actually working for anyone? I haven't gotten it to work anymore, always 403 errors.

**Comment by Raainman** [comment]
Mine is working for a while now. I while back I cleared the accesstoken and the refreshtoken, and I think I got an email check after that. Been working smooth since. I use user agent 'TooGoodToGo'.

**Comment by c0lumb0** [comment]
> Mine is working for a while now. I while back (17 nov I think) I pulled a new version and cleared the accesstoken and the refreshtoken, and I think I got an email check after that. Been working smooth since. I use user agent 'TooGoodToGo'.

Tried this too...but I get the same error again..did you perform any other changes after pulling the new version?

**Comment by rayhvh** [comment]
I feel a bad programmer since i've tried to look into the API and find ways for automatic purchase, I didn't even find any endpoint to do so. I was trying to learn something. Not sell it or abuse it.

**Comment by Raainman** [comment]
Mine stopped working today :-(

**Comment by marklagendijk** [comment]
Please retry with the latest version (3.8.0) and login with either via the command line or via the Telegram bot.

**Comment by andrzejpodgorny** [comment]
Hmm, i logged into tgtg, but did not getting any notifications.

**Comment by Slothoncrack** [comment]
Thank you so much! It works again now. Hint to others: make sure to reset with `toogoodtogo-watcher config` first as the config layout has changed. Otherwise you'll see 403 or other errors.
I've just restarted monitoring, will see if there are any problems after one hour or so as another user has hinted

**Comment by lborruto** [comment]
> Please retry with the latest version (3.8.0) and login with either via the command line or via the Telegram bot.

Tried to log in with telegram, but it keep throwing me error 403 when I type `/login user@domain.com`.

`HTTPError: Reponse code 403 (Forbidden)\n at Request.<anonymous> (/home/node/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n at processTicksAndRejections (internal/pricess/task_queues.js:95:5)`

I also tried `config-reset` but same error.

**Comment by marklagendijk** [comment]
@lborruto does the login process report that it succeeded, or do you already get an error during the login process?

**Comment by lborruto** [comment]
> @lborruto does the login process report that it succeeded, or do you already get an error during the login process?

I got this message :
> Will start the login process with the specified email address: user@domain.com.
> Open the login email on your PC and click the link.
> Don't open the email on a phone that has the TooGoodToGo app installed. That won't work.
> When you clicked the link run:
> /login_continue

And then :
> HTTPError: Reponse code 403 (Forbidden)
> at Request.<anonymous> (/home/node/app/node_modules/got/dist/source/as-promise/index.js:117:42)
> at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by marklagendijk** [comment]
Did you get the error when you ran the `/login_continue` command?

**Comment by lborruto** [comment]
> Did you get the error when you ran the `/login_continue` command?

Nothing when I run the `/login_continue` command, but I didn't received any email in the first place.

**Comment by Frankdoc** [comment]
How are we supposed to set this up ( with the commands etc) if we run this on Docker ( synology) from DSM, not command line?

**Comment by marklagendijk** [comment]
> How are we supposed to set this up ( with the commands etc) if we run this on Docker ( synology) from DSM, not command line?

Via the Telegram bot.
