### ISSUE TITLE
Error after installing 

### ISSUE THREAD

**Issue by Hondai96** [marklagendijk/node-toogoodtogo-watcher#120]
I got the following error after installing and then asking the watcher for his version:
C:\Users\lschneid\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\conf\dist\source\index.js:289
            throw error;
            ^

SyntaxError: Unexpected string in JSON at position 415
    at JSON.parse (<anonymous>)
    at Conf._deserialize (C:\Users\lschneid\AppData\Roaming\npm\node_modules\[4mtoogoodtogo-watcher[24m\node_modules\[4mconf[24m\dist\source\index.js:67:43)
    at Conf.get store [as store] (C:\Users\lschneid\AppData\Roaming\npm\node_modules\[4mtoogoodtogo-watcher[24m\node_modules\[4mconf[24m\dist\source\index.js:277:43)
    at new Conf (C:\Users\lschneid\AppData\Roaming\npm\node_modules\[4mtoogoodtogo-watcher[24m\node_modules\[4mconf[24m\dist\source\index.js:130:32)
    at Object.<anonymous> (C:\Users\lschneid\AppData\Roaming\npm\node_modules\[4mtoogoodtogo-watcher[24m\lib\config.js:5:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:1072:14)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:937:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:778:12)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:961:19)[39m

Maybe you have an idea. Thank you =)

**Comment by FdjNL** [comment]
is your config valid json?

**Comment by marklagendijk** [comment]
Indeed an issue with your config file. Make sure you use valid JSON.
