### ISSUE TITLE
Error running container

### ISSUE THREAD

**Issue by williamledda** [marklagendijk/node-toogoodtogo-watcher#176]
Hi, 
I'm trying to run the watcher in a container and I get the following error:

```
/home/node/app/node_modules/conf/dist/source/index.js:289
            throw error;
            ^

SyntaxError: Unexpected token . in JSON at position 494
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/home/node/app/node_modules/conf/dist/source/index.js:67:43)
    at Conf.get store [as store] (/home/node/app/node_modules/conf/dist/source/index.js:277:43)
    at new Conf (/home/node/app/node_modules/conf/dist/source/index.js:130:32)
    at Object.<anonymous> (/home/node/app/lib/config.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```

This is the command that I run:

``docker run  --rm -it --name toogoodtogo-watcher  -e TZ=Europe/Amsterdam  -v <MYCONFIG_DIR>:/home/node/.config/toogoodtogo-watcher-nodejs  marklagendijk/toogoodtogo-watcher``

The same happens when running with docker compose using the example provided. This is the docker image I am using: ``marklagendijk/toogoodtogo-watcher   latest``

**Comment by williamledda** [comment]
Sorry it was a my mistake in the configuration file
