### ISSUE TITLE
RequestError: connect EHOSTUNREACH <IP>:443 with Docker

### ISSUE THREAD

**Issue by gblanc** [marklagendijk/node-toogoodtogo-watcher#216]
Hello,

Since last month, I have this error :

RequestError: connect EHOSTUNREACH 52.222.174.22:443
   at ClientRequest.<anonymous> (file:///home/node/app/node_modules/got/dist/source/core/index.js:789:107)
  at Object.onceWrapper (node:events:628:26)
  at ClientRequest.emit (node:events:525:35)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
   at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
   at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
Error during request:
POST https://apptoogoodtogo.com/api/item/v8/
 undefined

I run in docker mode, with last version.

Is it because of the switch to V8 of API ?

thanks a lot !

**Comment by zeus24** [comment]
What version? Today, a few days ago, and a week ago serveral updates were published.

**Comment by marklagendijk** [comment]
Looks like a networking issue.
Try removing the container, and recreating it.

**Comment by gblanc** [comment]
Hello Mark, I have removed container and recreated it and I have the same issue : 
toogoodtogo-watcher_1  | RequestError: connect EHOSTUNREACH 13.249.9.103:443
toogoodtogo-watcher_1  |     at ClientRequest.<anonymous> (file:///home/node/app/node_modules/got/dist/source/core/index.js:789:107)
toogoodtogo-watcher_1  |     at Object.onceWrapper (node:events:628:26)
toogoodtogo-watcher_1  |     at ClientRequest.emit (node:events:525:35)
toogoodtogo-watcher_1  |     at TLSSocket.socketErrorListener (node:_http_client:502:9)
toogoodtogo-watcher_1  |     at TLSSocket.emit (node:events:513:28)
toogoodtogo-watcher_1  |     at emitErrorNT (node:internal/streams/destroy:151:8)
toogoodtogo-watcher_1  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
toogoodtogo-watcher_1  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
toogoodtogo-watcher_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

Note that it work once and after I have this error. So, it means that I can connect but after it's as if I was blocked ?

@zeus24 : I'm using the last version of the day (docker pull down before)
