### ISSUE TITLE
error 401

### ISSUE THREAD

**Issue by laurentdu56** [marklagendijk/node-toogoodtogo-watcher#225]
hi,

i've got a 401 error since today.
i update the watcher. i also try to change the datadome cookie like for 403 error but it dont work :(

HTTPError: Response code 401 ()
    at Request.<anonymous> (file:///C:/Users/laure/AppData/Roaming/npm/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:640:26)
    at Request.emit (node:events:532:35)
    at Request._onResponseBase (file:///C:/Users/laure/AppData/Roaming/npm/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:726:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Request._onResponse (file:///C:/Users/laure/AppData/Roaming/npm/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:765:13)

someone could help me ?

have a nice day

**Comment by laurentdu56** [comment]
i think as i updated, i just have to login my email an other time
now it's work
