### ISSUE TITLE
Login HttpError 403

### ISSUE THREAD

**Issue by luccalb** [marklagendijk/node-toogoodtogo-watcher#237]
When i try to login using `toogoodtogo-watcher login --email=<email>` i receive the following error:
```{bash}
Something went wrong: HTTPError: Response code 403 ()
    at Request.<anonymous> (file:///home//.local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:628:26)
    at Request.emit (node:events:525:35)
    at Request._onResponseBase (file:///home//.local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:727:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Request._onResponse (file:///home//.local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:766:13)
```
Repeating the login POST request in Postman, shows an additional error : "Please enable JS and disable any ad blocker".
Am I the only one having this issue? Today I was also asked to do a captcha when logging into the app.

**Comment by Pferdefluesterer** [comment]
got the same error

**Comment by luccalb** [comment]
I tried to log in again today and it worked, without changing anything.. Will close this Issue for now.
