### ISSUE TITLE
Err 403

### ISSUE THREAD

**Issue by jfadeuilhe** [marklagendijk/node-toogoodtogo-watcher#239]
Hello !

Above all, thank you again for this great tool that we use and share with friends and family (6 active bots on my Synology!)

Since midnight today, all my toogoodtogo-watcher watch show in error log:

HTTPError: Response code 403 ()
    at Request.<anonymous> (file:///usr/local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:628:26)
    at Request.emit (node:events:525:35)
    at Request._onResponseBase (file:///usr/local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:727:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._onResponse (file:///usr/local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:766:13)

Do you have any idea what's going on?

Best regards
Jacques

**Comment by DzianisMakeichyk** [comment]
I assume it was related to the fact that they introduced anti-spam system and it required solving captcha

**Comment by jfadeuilhe** [comment]
Yes, that's what I'm assuming too.

Obviously there should no longer be an operational alert system, the baskets go less quickly...

**Comment by jfadeuilhe** [comment]
It's been working again for several weeks now, as long as it lasts!
