### ISSUE TITLE
HTTPError: Response code 403

### ISSUE THREAD

**Issue by polish96** [marklagendijk/node-toogoodtogo-watcher#245]
When attempting to execute the application with the command `toogoodtogo-watcher watch`, I encounter this error message:

```
Error during request:
POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
undefined

HTTPError: Response code 403 ()
    at Request.<anonymous> (file:///C:/Users/4851/AppData/Roaming/npm/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:629:26)
    at Request.emit (node:events:526:35)
    at Request._onResponseBase (file:///C:/Users/4851/AppData/Roaming/npm/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:727:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._onResponse (file:///C:/Users/4851/AppData/Roaming/npm/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:766:13)
```
    
To solve the problem, I tried uninstalling Node.js and then reinstalling it. Next, I installed the application using `npm install -g toogoodtogo-watcher` and modified the "config" file according to the instructions using `toogoodtogo-watcher config`. Then, I logged in using `toogoodtogo-watcher login --email mail@example.com` and confirmed the link that was sent to my email. The login process was successful. However, despite all these steps, the same error message continues to appear.

**Comment by polish96** [comment]
Yesterday, the application started working automatically, and new notifications were coming in. However, since this morning, an error message has been displayed again, and there are no new notifications.

**Comment by c0lumb0** [comment]
I encountered the same error message, more or less.
It then disappeared for some days and notifications were working just fine and now they are appearing again for the 2nd day in a row.

This reminds me of

https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/212
https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/201

I think it is related to datadome protection again.

**Comment by depablo** [comment]
My observation is that a single token is valid for 500 API calls, so after that, it requires a refresh.
I investigated it with my logs.

**Comment by KSuondProject** [comment]
Hi,
Today this problem comes again:

```
Error during request:
POST https://apptoogoodtogo.com/api/item/v8/
undefined

HTTPError: Response code 403 ()
    at Request.<anonymous> (file:///usr/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:633:26)
    at Request.emit (node:events:530:35)
    at Request._onResponseBase (file:///usr/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:727:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Request._onResponse (file:///usr/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:766:13)
```

Someone else has this problem?

**Comment by DMW007** [comment]
> Someone else has this problem?

Hi,
yes, I'd multiple 403 requests in the logs. No notifications about changes for over 24 hours. We also had a larger internet outtake during this period, so I didn't wondering for a while.

I tried stopping the application for 1 hour and changed the poll interval from 30s to 60s in case the requests hits any limit - normally not the case when receiving http 403. But it's worth a try. Unfortunately, it didn't work.

I didn't try re-authentication yet, maybe this could help. Otherwise it would be required to have a deeper look in the API infrastructure, maybe with re-reverse-engineering the mobile app.

**Comment by c0lumb0** [comment]
Did someone try changing the URL to v9 already?

Sometimes TGTG perform small changes like that.

**Comment by c0lumb0** [comment]
Possible solution should be available here: https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/261

**Comment by casudo** [comment]
v4.0.8 fixed the problem for me.

**Comment by polish96** [comment]
> v4.0.8 fixed the problem for me.

**Comment by polish96** [comment]
> v4.0.8 fixed the problem for me.
