### ISSUE TITLE
404 Error on /login

### ISSUE THREAD

**Issue by Gamax42** [marklagendijk/node-toogoodtogo-watcher#253]
Hello,
I'm getting a 404 error on /login via Telegram bot.

```
"HTTPError: Response code 404 (Not Found)\n    
at Request.<anonymous> (file:///home/node/app/node_modules/got/dist/source/as-promise/index.js:86:42)\n   
at Object.onceWrapper (node:events:632:26)\n    
at Request.emit (node:events:529:35)\n    
at Request._onResponseBase (file:///home/node/app/node_modules/got/dist/source/core/index.js:726:22)\n    
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    
at async Request._onResponse (file:///home/node/app/node_modules/got/dist/source/core/index.js:765:13)"
```

I'm using the docker image which is 10 months old, has the TGTG Api changed since then ? Should the docker image be updated with the most recent commits ?

**Comment by PtiBen69** [comment]
same problem.

**Comment by TP8609** [comment]
Check if you have the newest version api version changed from v3 to v4 
See https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/252
