### ISSUE TITLE
Issue: HTTPError: Response code 404 (Not Found) 

### ISSUE THREAD

**Issue by bokkoman** [marklagendijk/node-toogoodtogo-watcher#45]
Hi all.

I'm getting this new error.
Maybe they changed something on the API or website?

```
HTTPError: Response code 404 (Not Found) 
at onResponse (/home/node/app/node_modules/got/dist/source/as-promise/index.js:142:28)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by bokkoman** [comment]
I didn't read the closed issues, and found out that there was an update.
