### ISSUE TITLE
Fails if proxy server is used (no dns)

### ISSUE THREAD

**Issue by ThorstenEnghave** [marklagendijk/node-toogoodtogo-watcher#56]
How do you add a proxy-server to the config of connection ?
I have a proxy server, that also handle DNS, and the connection fails:

RequestError: getaddrinfo ENOTFOUND apptoogoodtogo.com
    at ClientRequest.<anonymous> (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\got\dist\source\core\index.js:953:111)
    at Object.onceWrapper (events.js:297:20)
    at ClientRequest.emit (events.js:214:15)
    at ClientRequest.origin.emit (C:\Users\xxxxxx\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)

**Comment by ThorstenEnghave** [comment]
Website blicked by company policy
